# Generated by Django 4.1.7 on 2023-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True, null=True)),
                ('last_message_sent', models.CharField(max_length=1000000000000)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pic')),
            ],
        ),
    ]
